on:
  push:
    branches:
      - master
      - main

jobs:
  lint:
    name: hadolint
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: hadolint Dockerfile
        
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    container: pipelinecomponents/yamllint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: yamllint .
