on:
  push:
    branches:
      - master
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: hadolint Dockerfile
