---
name: pipelinecomponents

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main

jobs:
  lint:
    name: hadolint
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: hadolint Dockerfile

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    container: pipelinecomponents/yamllint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        run: yamllint .

  jsonlint:
    name: jsonlint
    runs-on: ubuntu-latest
    container: pipelinecomponents/jsonlint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run jsonlint
        run: |
          find . -not -path './.git/*' -name '*.json' -type f -print0 |
          parallel --will-cite -k -0 -n1 jsonlint
